### PR TITLE
adding windows quad support

### PR DESCRIPTION
**Pull request by SwayamInSync**
Adding quad build of SLEEF for windows (missed in #9 )

### CODE REVIEW

**Comment by SwayamInSync** [comment]
@conda-forge-admin, please add bot automerge

**Comment by SwayamInSync** [comment]
@bluescarni can you check this one too 🙂 if all good

**Comment by bluescarni** [comment]
LGTM, merging. Thanks @SwayamInSync !

**Comment by SwayamInSync** [comment]
Any idea how much time it takes to get available through conda-forge channel?

**Comment by bluescarni** [comment]
> Any idea how much time it takes to get available through conda-forge channel?

In my experience it usually takes something like a couple of hours or so after the CI of the feedstock on the main branch has concluded.

**Pull request merged**
